/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.globalprogramacionii.igu;

/**
 *
 * @author cande
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnSocios = new javax.swing.JButton();
        BtnColectivos = new javax.swing.JButton();
        BtnViaje = new javax.swing.JButton();
        BtnIntercambiar = new javax.swing.JButton();
        BtnMayorKm = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MENÚ");

        BtnSocios.setText("Ver información sobre socios");
        BtnSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSociosActionPerformed(evt);
            }
        });

        BtnColectivos.setText("Ver información sobre colectivos");
        BtnColectivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColectivosActionPerformed(evt);
            }
        });

        BtnViaje.setText("Registrar viaje");
        BtnViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViajeActionPerformed(evt);
            }
        });

        BtnIntercambiar.setText("Intercambiar colectivos");
        BtnIntercambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIntercambiarActionPerformed(evt);
            }
        });

        BtnMayorKm.setText("Ver vehiculo con mayor kilometraje");
        BtnMayorKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMayorKmActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnMayorKm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnIntercambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnViaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnColectivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(BtnSalir)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(BtnSocios)
                .addGap(18, 18, 18)
                .addComponent(BtnColectivos)
                .addGap(18, 18, 18)
                .addComponent(BtnViaje)
                .addGap(18, 18, 18)
                .addComponent(BtnIntercambiar)
                .addGap(18, 18, 18)
                .addComponent(BtnMayorKm)
                .addGap(18, 18, 18)
                .addComponent(BtnSalir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSociosActionPerformed
        // TODO add your handling code here:
        InformacionSocios infosoc = new InformacionSocios();
        infosoc.setVisible(true);
        infosoc.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_BtnSociosActionPerformed

    private void BtnViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViajeActionPerformed
        // TODO add your handling code here:
        RegistrarViaje regisviaje = new RegistrarViaje();
        regisviaje.setVisible(true);
        regisviaje.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnViajeActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
      
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnColectivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColectivosActionPerformed
        // TODO add your handling code here:
        InformacionVehiculos infove = new InformacionVehiculos();
        infove.setVisible(true);
        infove.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnColectivosActionPerformed

    private void BtnIntercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIntercambiarActionPerformed
        Intercambio intercambio = new Intercambio();
        intercambio.setVisible(true);
        intercambio.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnIntercambiarActionPerformed

    private void BtnMayorKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMayorKmActionPerformed
        MayorKm mayorkm = new MayorKm();
        mayorkm.setVisible(true);
        mayorkm.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnMayorKmActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnColectivos;
    private javax.swing.JButton BtnIntercambiar;
    private javax.swing.JButton BtnMayorKm;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSocios;
    private javax.swing.JButton BtnViaje;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
